version: '3'
services:

  db:
    build:
      context: ./app
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-app
    ports:
      - "8080:9080"
      - "8453:8453"
    links:
      - db